# Generated by Django 5.0.2 on 2024-02-12 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_item_sku"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="name",
            new_name="tags",
        ),
    ]
