# Generated by Django 5.0.2 on 2024-02-12 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_name_category_category_rename_name_tag_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="Category",
            new_name="category",
        ),
    ]
