# Generated by Django 5.0.2 on 2024-02-12 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_category_category_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tags",
            new_name="tag",
        ),
    ]
